### PR TITLE
Generate auto-completion in package build

### PR DESCRIPTION
**Pull request by ede1998**
Thanks for maintaining this fork.

I noticed that original `rip` does not offer completions and found your fork.

I modified the package build a bit so that to completions are now generated at package build time and nix will take care that they are available in the standard location that the shell expects. This means that after installation the completions should work out of the box without additional setup/

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Thanks!

Is there somewhere I can read about the `installShellCompletion` command? Also are there other projects that do something like this/is this the standard way?

**Comment by ede1998** [comment]
I also only found out about it today by looking at zellij packaging:
https://github.com/NixOS/nixpkgs/blob/d063c1dd113c91ab27959ba540c0d9753409edf3/pkgs/tools/misc/zellij/default.nix#L53-L56

The hook is documented here:
https://nixos.org/manual/nixpkgs/stable/#installshellfiles

Btw: The CI failure does not seem related to my PR.

**Comment by MilesCranmer** [comment]
Cool, thanks! And yeah just looks like coveralls gets turned off for external user-triggered CI, will need to fix eventually.

Is there a way the CI can detect if the shell completions were installed correctly or not? Here's the test:
https://github.com/MilesCranmer/rip2/blob/b87ad6c72c3ba04bd200cc0efa208e51b5cbfffc/.github/workflows/ci.yml#L60-L79. I want to make sure it's working correctly from the CI

**Comment by ede1998** [comment]
> Is there a way the CI can detect if the shell completions were installed correctly or not?

Is [this](https://github.com/MilesCranmer/rip2/pull/65/commits/32f9a88d03a58e331e6c338bb54266e62b6d867b) what you imagined?

It uses expect to interactively start a bash shell and press `TAB` to trigger completions, then checks that there are at least some available.

Do you need fish and zsh too? (Though I don't use those so might have some trouble.)

**Comment by MilesCranmer** [comment]
Brilliant! bash is fine. This is perfect, nice work!

**Comment by MilesCranmer** [comment]
Seems like the completion tests fail on Darwin. I'm happy to filter those tests if they aren't supposed to work, but if we expect them to work, I wonder what the issue is?

**Comment by ede1998** [comment]
I assumed that they would work. :/
Unfortunately, I don't have a darwin system to test with.
Maybe I can try with the Github CI in my fork.

My current theory is that the bootstrap script from `bash-completion` fails to source for some reason and my check does not detect it correctly. 

Also, I noticed in this log that my test could actually succeed when it should not if enough files are added to the repository. Will fix that too.

**Comment by ede1998** [comment]
Ok it should now finally work. The issue was that macOS ships an ancient `bash` version by default which is not supported by `bash-completion`.

**Comment by MilesCranmer** [comment]
Very nice, thanks!!

Will merge now. Hope you don't mind if I do a git squash so that it will be in conventional commit format, it makes things easier for the release CI to run.

**Comment by MilesCranmer** [comment]
P.S., in case you prefer nixpkgs, I added `rip2` to it: https://github.com/NixOS/nixpkgs/pull/353742. In theory I guess the automatic completions could be shipped there as well?

**Comment by ede1998** [comment]
Thank you, I missed the comment before.

I'll check it out and see if I can add the completions there too if still needed.

**Pull request merged**
